import {
  LayoutDashboard,
  Sprout,
  List,
  Users,
  Megaphone,
  Wallet,
  User,
  UserCheck,
  Package,
  AlertTriangle,
  DollarSign,
  BarChart3,
  Settings,
  FileText,
  ShoppingCart,
  TrendingUp,
  RefreshCw,
  CreditCard,
  Star,
  Bell,
  HelpCircle,
} from "lucide-react";

export const farmerNav = [
  { to: "/farmer", label: "Dashboard", icon: LayoutDashboard, end: true },
  { to: "/farmer/assets", label: "Assets", icon: Sprout },
  { to: "/farmer/listings", label: "Listings", icon: List },
  { to: "/farmer/investors", label: "Investors", icon: Users },
  // { to: "/farmer/updates", label: "Updates", icon: Megaphone },
  // { to: "/farmer/wallet", label: "Wallet", icon: Wallet },
  { to: "/farmer/profile", label: "Profile", icon: User },
  // { to: "/farmer/support", label: "Help", icon: HelpCircle },
];
export const adminNav = [
  {
    to: "/admin",
    label: "Dashboard",
    icon: LayoutDashboard,
    badge: 0,
    end: true,
  },
  {
    to: "/admin/farmers",
    label: "Farmer Verifications",
    icon: UserCheck,
    badge: 12,
  },
  {
    to: "/admin/assets",
    label: "Asset Verifications",
    icon: Package,
    badge: 6,
  },
  { to: "/admin/risk", label: "Risk Monitor", icon: AlertTriangle, badge: 5 },
  {
    to: "/admin/refunds",
    label: "Refund Requests",
    icon: DollarSign,
    badge: 7,
  },
  { to: "/admin/analytics", label: "Analytics", icon: BarChart3, badge: 0 },
  // { to: "/operations", label: "Operations", icon: Settings, badge: 0 },
  { to: "/admin/users", label: "User Management", icon: Users, badge: 0 },
  { to: "/admin/profile", label: "Profile", icon: User },
  // { to: "/logs", label: "System Logs", icon: FileText, badge: 0 },
];

export const investorNav = [
  { to: "/investor", label: "Dashboard", icon: LayoutDashboard, end: true },
  { to: "/investor/marketplace", label: "Marketplace", icon: ShoppingCart },
  { to: "/investor/investments", label: "Investments", icon: TrendingUp },
  { to: "/investor/distributions", label: "Distributions", icon: DollarSign },
  { to: "/investor/refunds", label: "Refund Requests", icon: RefreshCw },
  { to: "/investor/wallet", label: "Wallet", icon: CreditCard },
  // { to: "/investor/reviews", label: "My Reviews", icon: Star },
  { to: "/investor/notifications", label: "Notifications", icon: Bell },
  { to: "/investor/profile", label: "Profile", icon: User },
];
