// Centralized mock data for the AgriShare admin portal.
export const KPIS = {
  totalUsers: {
    value: 1247,
    trend: 12,
    breakdown: { Farmers: 892, Investors: 342, Admins: 13 },
  },
  activeListings: {
    value: 45,
    trend: 8,
    breakdown: { Funded: 28, Active: 12, Failed: 5 },
  },
  investmentVolume: { value: 12_500_000, trend: 23 },
  pendingVerifications: { value: 18, breakdown: { Farmers: 12, Assets: 6 } },
  pendingRefunds: { value: 7, urgent: 3 },
  platformRevenue: { value: 187_500, trend: 15 },
};

export const REVENUE_SERIES = Array.from({ length: 30 }, (_, i) => {
  const base = 4500 + Math.sin(i / 3) * 1200 + i * 110;
  return {
    date: new Date(2026, 3, i + 1).toISOString().slice(5, 10),
    revenue: Math.round(base + Math.random() * 800),
    investments: Math.round(base * 8 + Math.random() * 5000),
  };
});

export const RECENT_ACTIVITY = [
  {
    admin: "Teklehiwot M.",
    action: "verified farmer",
    target: "Abebe Kebede",
    at: new Date(Date.now() - 2 * 60_000).toISOString(),
  },
  {
    admin: "Yodit S.",
    action: "verified asset",
    target: "Teff Farm — Gozamin",
    at: new Date(Date.now() - 60 * 60_000).toISOString(),
  },
  {
    admin: "Daniel A.",
    action: "processed refund for",
    target: "Tigist Hailu",
    at: new Date(Date.now() - 3 * 60 * 60_000).toISOString(),
  },
  {
    admin: "Teklehiwot M.",
    action: "rejected listing",
    target: "Sorghum Farm — Tigray",
    at: new Date(Date.now() - 5 * 60 * 60_000).toISOString(),
  },
  {
    admin: "Selam T.",
    action: "suspended user",
    target: "investor #4421",
    at: new Date(Date.now() - 9 * 60 * 60_000).toISOString(),
  },
  {
    admin: "Daniel A.",
    action: "approved bulk verification",
    target: "12 farmers",
    at: new Date(Date.now() - 26 * 60 * 60_000).toISOString(),
  },
];

export const SYSTEM_STATUS = {
  mongo: { ok: true, label: "Connected", lastBackup: "2 hours ago" },
  blockchain: { ok: true, label: "Synced", block: "4,521,345" },
  api: { ok: false, label: "124ms", warn: true },
  uptime: "99.94%",
  events: [
    { type: "deploy", text: "v2.4.1 deployed", at: "12 mins ago" },
    { type: "info", text: "Edge function cold start", at: "2 hours ago" },
    { type: "warn", text: "API latency spike resolved", at: "yesterday" },
  ],
};

export const TOP_LISTINGS = [
  { name: "Teff Farm — Gozamin", raised: 0.92, amount: 460_000 },
  { name: "Coffee Plantation — Jimma", raised: 0.78, amount: 780_000 },
  { name: "Dairy Cattle Herd — Bishoftu", raised: 0.64, amount: 320_000 },
  { name: "Wheat Cooperative — Bale", raised: 0.51, amount: 510_000 },
  { name: "Beekeeping — Wollega", raised: 0.42, amount: 84_000 },
];

export const PENDING_FARMERS = [
  {
    id: "FYD-123456",
    name: "Bekele Tadesse",
    email: "bekele@example.com",
    phone: "+251 911 234 567",
    region: "Amhara",
    zone: "East Gojjam",
    woreda: "Gozamin",
    kebele: "01",
    submittedAt: "2026-04-25",
    status: "pending",
  },
  {
    id: "FYD-234567",
    name: "Tigist Worku",
    email: "tigist@example.com",
    phone: "+251 922 345 678",
    region: "Oromia",
    zone: "Jimma",
    woreda: "Limu Kosa",
    kebele: "04",
    submittedAt: "2026-04-24",
    status: "pending",
  },
  {
    id: "FYD-345678",
    name: "Mulugeta Desta",
    email: "mulugeta@example.com",
    phone: "+251 933 456 789",
    region: "SNNPR",
    zone: "Sidama",
    woreda: "Aleta Wondo",
    kebele: "07",
    submittedAt: "2026-04-23",
    status: "pending",
  },
  {
    id: "FYD-456789",
    name: "Hanna Abebe",
    email: "hanna@example.com",
    phone: "+251 944 567 890",
    region: "Amhara",
    zone: "South Gondar",
    woreda: "Farta",
    kebele: "02",
    submittedAt: "2026-04-22",
    status: "pending",
  },
  {
    id: "FYD-567890",
    name: "Yonas Teshome",
    email: "yonas@example.com",
    phone: "+251 955 678 901",
    region: "Oromia",
    zone: "West Shewa",
    woreda: "Ambo",
    kebele: "11",
    submittedAt: "2026-04-22",
    status: "pending",
  },
  {
    id: "FYD-678901",
    name: "Selamawit Hailu",
    email: "selam@example.com",
    phone: "+251 966 789 012",
    region: "Tigray",
    zone: "Central",
    woreda: "Adwa",
    kebele: "03",
    submittedAt: "2026-04-21",
    status: "pending",
  },
  {
    id: "FYD-789012",
    name: "Tesfaye Lemma",
    email: "tesfaye@example.com",
    phone: "+251 977 890 123",
    region: "SNNPR",
    zone: "Wolayita",
    woreda: "Sodo",
    kebele: "05",
    submittedAt: "2026-04-21",
    status: "pending",
  },
  {
    id: "FYD-890123",
    name: "Meron Girma",
    email: "meron@example.com",
    phone: "+251 988 901 234",
    region: "Amhara",
    zone: "North Wollo",
    woreda: "Lalibela",
    kebele: "08",
    submittedAt: "2026-04-20",
    status: "verified",
  },
  {
    id: "FYD-901234",
    name: "Dawit Bekele",
    email: "dawit@example.com",
    phone: "+251 999 012 345",
    region: "Oromia",
    zone: "Arsi",
    woreda: "Asela",
    kebele: "06",
    submittedAt: "2026-04-20",
    status: "pending",
  },
  {
    id: "FYD-012345",
    name: "Aster Mengistu",
    email: "aster@example.com",
    phone: "+251 910 123 456",
    region: "Amhara",
    zone: "Awi",
    woreda: "Dangila",
    kebele: "09",
    submittedAt: "2026-04-19",
    status: "rejected",
  },
  {
    id: "FYD-112233",
    name: "Solomon Kassa",
    email: "solomon@example.com",
    phone: "+251 921 234 567",
    region: "Oromia",
    zone: "Borena",
    woreda: "Yabelo",
    kebele: "12",
    submittedAt: "2026-04-18",
    status: "pending",
  },
  {
    id: "FYD-223344",
    name: "Lemlem Gebre",
    email: "lemlem@example.com",
    phone: "+251 932 345 678",
    region: "Tigray",
    zone: "South",
    woreda: "Maychew",
    kebele: "10",
    submittedAt: "2026-04-18",
    status: "pending",
  },
];

export const PENDING_ASSETS = [
  {
    id: "AST-001",
    name: "Teff Farm — Gozamin",
    type: "Farmland",
    farmer: "Abebe Kebede",
    region: "Amhara",
    submittedAt: "2026-04-26",
    status: "pending",
    size: "12 hectares",
    soil: "Vertisol",
    water: "River-fed",
    desc: "Highland teff plot with mature soil and reliable seasonal rainfall.",
  },
  {
    id: "AST-002",
    name: "Dairy Cattle Herd",
    type: "Livestock",
    farmer: "Bekele Tadesse",
    region: "Oromia",
    submittedAt: "2026-04-25",
    status: "pending",
    animal: "Cattle",
    breed: "Holstein × Boran",
    count: 24,
    desc: "Mixed herd raised for milk production with vaccination records.",
  },
  {
    id: "AST-003",
    name: "Coffee Plantation — Jimma",
    type: "Farmland",
    farmer: "Tigist Worku",
    region: "Oromia",
    submittedAt: "2026-04-24",
    status: "pending",
    size: "8 hectares",
    soil: "Nitisol",
    water: "Spring-fed",
    desc: "Shaded Arabica plantation in the Jimma forest belt.",
  },
  {
    id: "AST-004",
    name: "Goat Herd — Borena",
    type: "Livestock",
    farmer: "Solomon Kassa",
    region: "Oromia",
    submittedAt: "2026-04-23",
    status: "pending",
    animal: "Goat",
    breed: "Borana",
    count: 60,
    desc: "Pastoralist herd with rotation grazing.",
  },
  {
    id: "AST-005",
    name: "Wheat Farm — Bale",
    type: "Farmland",
    farmer: "Yonas Teshome",
    region: "Oromia",
    submittedAt: "2026-04-22",
    status: "pending",
    size: "20 hectares",
    soil: "Andosol",
    water: "Rain-fed",
    desc: "Highland wheat cooperative plot with cooperative storage.",
  },
  {
    id: "AST-006",
    name: "Beekeeping — Wollega",
    type: "Livestock",
    farmer: "Meron Girma",
    region: "Oromia",
    submittedAt: "2026-04-22",
    status: "pending",
    animal: "Bees",
    breed: "Apis mellifera",
    count: 80,
    desc: "80 modern hives, eucalyptus forage.",
  },
  {
    id: "AST-007",
    name: "Sesame Farm — Humera",
    type: "Farmland",
    farmer: "Lemlem Gebre",
    region: "Tigray",
    submittedAt: "2026-04-21",
    status: "verified",
    size: "15 hectares",
    soil: "Cambisol",
    water: "Rain-fed",
    desc: "Lowland sesame export-grade plot.",
  },
  {
    id: "AST-008",
    name: "Sheep Flock — Menz",
    type: "Livestock",
    farmer: "Hanna Abebe",
    region: "Amhara",
    submittedAt: "2026-04-20",
    status: "pending",
    animal: "Sheep",
    breed: "Menz",
    count: 45,
    desc: "Highland sheep flock for wool and mutton.",
  },
];

export const RISK_LISTINGS = [
  {
    id: "LST-101",
    title: "Teff Farm Expansion",
    farmer: "Abebe Kebede",
    goal: 500_000,
    raised: 145_000,
    days: 8,
  },
  {
    id: "LST-102",
    title: "Goat Farming Co-op",
    farmer: "Solomon Kassa",
    goal: 250_000,
    raised: 95_000,
    days: 5,
  },
  {
    id: "LST-103",
    title: "Wheat Farm Project",
    farmer: "Yonas Teshome",
    goal: 1_000_000,
    raised: 310_000,
    days: 12,
  },
  {
    id: "LST-104",
    title: "Sorghum Cooperative",
    farmer: "Lemlem Gebre",
    goal: 400_000,
    raised: 80_000,
    days: 3,
  },
  {
    id: "LST-105",
    title: "Highland Honey Project",
    farmer: "Meron Girma",
    goal: 200_000,
    raised: 110_000,
    days: 9,
  },
];

export const REFUND_REQUESTS = [
  {
    id: "REQ-001",
    investor: "Abebe Kebede",
    farmer: "Tigist Worku",
    listing: "Teff Farm",
    amount: 15_000,
    shares: 15,
    requestedAt: "2026-04-20",
    status: "pending",
    reason: "Farmer missed milestone deadline.",
  },
  {
    id: "REQ-002",
    investor: "Tigist Hailu",
    farmer: "Bekele Tadesse",
    listing: "Coffee Plantation",
    amount: 25_000,
    shares: 25,
    requestedAt: "2026-04-21",
    status: "pending",
    reason: "Project cancelled by farmer.",
  },
  {
    id: "REQ-003",
    investor: "Mulugeta Desta",
    farmer: "Solomon Kassa",
    listing: "Dairy Cattle",
    amount: 10_000,
    shares: 10,
    requestedAt: "2026-04-22",
    status: "pending",
    reason: "Insufficient progress reports.",
  },
  {
    id: "REQ-004",
    investor: "Hanna Abebe",
    farmer: "Yonas Teshome",
    listing: "Wheat Farm",
    amount: 40_000,
    shares: 40,
    requestedAt: "2026-04-22",
    status: "pending",
    reason: "Investor change of plans.",
  },
  {
    id: "REQ-005",
    investor: "Dawit Bekele",
    farmer: "Lemlem Gebre",
    listing: "Sesame Farm",
    amount: 8_000,
    shares: 8,
    requestedAt: "2026-04-23",
    status: "pending",
    reason: "Listing failed to fund.",
  },
  {
    id: "REQ-006",
    investor: "Aster Mengistu",
    farmer: "Meron Girma",
    listing: "Beekeeping",
    amount: 12_000,
    shares: 12,
    requestedAt: "2026-04-24",
    status: "pending",
    reason: "Force majeure.",
  },
  {
    id: "REQ-007",
    investor: "Yodit Solomon",
    farmer: "Hanna Abebe",
    listing: "Sheep Flock",
    amount: 18_000,
    shares: 18,
    requestedAt: "2026-04-24",
    status: "pending",
    reason: "Withdrawn.",
  },
];

export const INVESTMENT_TIME = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(2026, 3, i + 1).toISOString().slice(5, 10),
  amount: Math.round(
    60_000 + Math.sin(i / 4) * 25_000 + i * 1500 + Math.random() * 15000,
  ),
  contracts: Math.round(2 + Math.random() * 5),
}));

export const TOP_LISTINGS_INVEST = [
  { name: "Teff Farm", invested: 600_000, contracts: 16 },
  { name: "Coffee Plantation", invested: 540_000, contracts: 14 },
  { name: "Dairy Cattle", invested: 410_000, contracts: 11 },
  { name: "Wheat Farm", invested: 360_000, contracts: 9 },
  { name: "Sesame Farm", invested: 240_000, contracts: 7 },
];

export const DISTRIBUTION_MONTHLY = [
  { month: "Nov", amount: 320_000 },
  { month: "Dec", amount: 480_000 },
  { month: "Jan", amount: 410_000 },
  { month: "Feb", amount: 620_000 },
  { month: "Mar", amount: 740_000 },
  { month: "Apr", amount: 880_000 },
];

export const CONTRACT_STATUS = [
  { name: "Active", value: 112 },
  { name: "Completed", value: 245 },
  { name: "Refunded", value: 44 },
];

export const CREDITS_BY_TYPE = [
  { type: "Monthly Reset", count: 62, volume: 620 },
  { type: "Signup Bonus", count: 45, volume: 450 },
  { type: "Bundle Purchase", count: 23, volume: 230 },
  { type: "Adjustment", count: 9, volume: 35 },
];

export const CREDITS_OVER_TIME = Array.from({ length: 14 }, (_, i) => ({
  date: `D-${14 - i}`,
  positive: Math.round(20 + Math.random() * 40),
  negative: -Math.round(5 + Math.random() * 20),
}));

export const USERS = [
  {
    id: 1,
    name: "Abebe Kebede",
    email: "abebe@agri.et",
    role: "Farmer",
    status: "active",
    joined: "2026-01-12",
    lastActive: "2 hours ago",
  },
  {
    id: 2,
    name: "Tigist Hailu",
    email: "tigist@agri.et",
    role: "Investor",
    status: "active",
    joined: "2026-01-22",
    lastActive: "1 day ago",
  },
  {
    id: 3,
    name: "Teklehiwot M.",
    email: "tek@agri.et",
    role: "Admin",
    status: "active",
    joined: "2025-11-04",
    lastActive: "just now",
  },
  {
    id: 4,
    name: "Bekele Tadesse",
    email: "bekele@agri.et",
    role: "Farmer",
    status: "active",
    joined: "2026-02-09",
    lastActive: "yesterday",
  },
  {
    id: 5,
    name: "Yodit Solomon",
    email: "yodit@agri.et",
    role: "Investor",
    status: "active",
    joined: "2026-02-15",
    lastActive: "3 hours ago",
  },
  {
    id: 6,
    name: "Daniel Alemu",
    email: "daniel@agri.et",
    role: "Admin",
    status: "active",
    joined: "2025-12-01",
    lastActive: "20 mins ago",
  },
  {
    id: 7,
    name: "Mulugeta Desta",
    email: "mulu@agri.et",
    role: "Investor",
    status: "inactive",
    joined: "2026-03-03",
    lastActive: "2 weeks ago",
  },
  {
    id: 8,
    name: "Hanna Abebe",
    email: "hanna@agri.et",
    role: "Farmer",
    status: "active",
    joined: "2026-03-19",
    lastActive: "5 hours ago",
  },
  {
    id: 9,
    name: "Selam T.",
    email: "selam@agri.et",
    role: "Admin",
    status: "active",
    joined: "2026-01-08",
    lastActive: "1 hour ago",
  },
  {
    id: 10,
    name: "Yonas Teshome",
    email: "yonas@agri.et",
    role: "Farmer",
    status: "active",
    joined: "2026-04-01",
    lastActive: "today",
  },
];

export const PIE_COLORS = [
  "#2E7D32",
  "#4CAF50",
  "#F44336",
  "#FF9800",
  "#6B21A8",
  "#2196F3",
];
